server:
  port: 5000

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
        - id: JOB-POST-SERVICE
          uri: lb://JOB-POST-SERVICE  # Ensure this matches the Eureka registration name
          predicates:
            - Path=/api/v1/job-post/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials, Access-Control-Allow-Origin
      globalcors:
        cors-configuration:
          '[/**]':
            allowOrigins: "*"
            allowMethods: "*"
            allowHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
